# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/docs/examples/009_mcp_agent.ipynb.

# %% auto 0
__all__ = ['mcp_tool_selector', 'res', 'execute_tool', 'has_tool_calls']

# %% ../../nbs/docs/examples/009_mcp_agent.ipynb 4
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field
from .. import Define, V, E, Condition
from ..chat import Chat
import os

from fastmcp import Client


# %% ../../nbs/docs/examples/009_mcp_agent.ipynb 12
# Chat node for tool selection with MCP tools
# This chat will be used in the diagram to select tools
mcp_tool_selector = Chat(
    model="gpt-4o-mini",
    messages=[
        {"role": "user", "content": "{{user_query}}"}
    ],
    mcp_tools=mcp_tools,
    log_prompt=True
)

res = Chat(
    model="gpt-4o-mini",
    messages=[
        {"role": "user", "content": "{{user_query}}"},
        {"role": "function", "name": "{{tool_name}}", "content": "{{tool_response_text}}"},
    ]        
)

# %% ../../nbs/docs/examples/009_mcp_agent.ipynb 14
async def execute_tool(llm_response):
    """
    Extracts the tool name and arguments from the first tool_call in the LLM response,
    executes the tool via mcp_client, and returns the tool response text.
    """
    tool_calls = llm_response['content'].get('tool_calls', [])
    if not tool_calls:
        raise ValueError("No tool calls found in LLM response.")
    tool_name = tool_calls[0]['name']
    tool_args = tool_calls[0]['input']  # Already a dict
    async with mcp_client:
        tool_response = await mcp_client.call_tool(tool_name, tool_args)
        tool_response_text = tool_response.content[0].text
    return tool_response_text



# %% ../../nbs/docs/examples/009_mcp_agent.ipynb 15
# Condition to check if tools were selected
#we would do for each in a diagram
# Condition if use tools otherwise end
def has_tool_calls(llm_response):
    # for now don't check anything
    if llm_response.get('tool_use') is not None:
        return True
    return True



# %% ../../nbs/docs/examples/009_mcp_agent.ipynb 17
# Create the MCP Agent diagram
with Define('MCP Agent', type='decision') as MCPAgent:
    # Start: User query comes in
    # Select tool: Chat with MCP tools to decide which tool to use
    V('select_tool', mcp_tool_selector,
      inputs=['Start(user_query=.)'],
      outputs=[
          ('End'),
          ('execute_tool', Condition(has_tool_calls,'(0=content)'))
      ])
    
    # Execute the selected tool
    V('execute_tool', execute_tool,
      #outputs=['format_result(tool_result=.)']
      )
    E('execute_tool->End')
    # # Format tool result for summary
    # V('format_result', format_message,
    #   inputs=['execute_tool(tool_call=.)'],
    #   outputs=['another_chat()'])

    
