# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/docs/examples/009_mcp_agent.ipynb.

# %% auto 0
__all__ = ['tool_selector', 'has_tool_calls', 'MCP_Chat_factory']

# %% ../../nbs/docs/examples/009_mcp_agent.ipynb 4
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field
from .. import Define, V, E, Condition, Scope
from ..chat import Chat
import os

from fastmcp import Client
import asyncio


# %% ../../nbs/docs/examples/009_mcp_agent.ipynb 11
# Chat node for tool selection with MCP tools
# This chat will be used in the diagram to select tools
tool_selector = Chat(
    model="gpt-4o-mini",
    mcp_tools=mcp_tools,
)


# %% ../../nbs/docs/examples/009_mcp_agent.ipynb 17
# Condition to check if tools were selected
#we would do for each in a diagram
# Condition if use tools otherwise end
def has_tool_calls(llm_response):
    tool_call = llm_response['tool_calls']
    # for now don't check anything
    if tool_call != []:
        return True
    return False



# %% ../../nbs/docs/examples/009_mcp_agent.ipynb 19
def MCP_Chat_factory(mcp_tool_selector_chat,execute_mcp_tool):
    # Factory that returns the MCP Agent diagram definition
    with Define('MCP Agent', type='decision') as MCP_Chat:
        # Start: User query comes in
        # Select tool: Chat with MCP tools to decide which tool to use
        V('select_tool', mcp_tool_selector_chat,
          inputs=['Start(messages=.)'],
          outputs=[
              ('format_chat_messages'),
              ('Start_flow(tools=content)', Condition(stump_has_tool_calls, '(0=content)'))
          ])
        V('format_chat_messages', format_chat_messages,
          outputs=['End(messages = .)'])
        # Execute the selected tool
        V('Start_flow',
        )
        with Scope('flow'):
            V('execute_tool', execute_mcp_tool,
              inputs=['Start_flow(tool = tools)'],
              outputs=['End_flow'],
              for_each=['tool']
            )
            # Format the final answer for the user
        V('End_flow',
          outputs=['End(messages = .)'])
    return MCP_Chat
